project_root <- here::here()
sites <- c("SICNU", "TJNU")
path_src <- fs::path(project_root, "sourcedata")
path_raw <- fs::path(project_root, "rawdata")
path_tmpl <- fs::path(project_root, "code", "template")
